### ISSUE TITLE
Unable to return cookies from chromium with error "call of reflect.Value.Float on zero Value"

### ISSUE THREAD

**Issue by sicko7947** [mxschmitt/playwright-go#119] opened 2021-04-23 18:56 UTC
panic: reflect: call of reflect.Value.Float on zero Value

goroutine 9 [running]:
reflect.Value.Float(...)
        C:/Program Files/Go/src/reflect/value.go:931
github.com/mxschmitt/playwright-go.remapValue(0x0, 0x0, 0x0, 0x130b260, 0xc00045b0c0, 0x182)
        C:/Users/sicko/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/helpers.go:138 +0xc05
github.com/mxschmitt/playwright-go.remapValue(0x134de80, 0xc0026a78f0, 0x15, 0x13f6cc0, 0xc00045b080, 0x199)
        C:/Users/sicko/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/helpers.go:158 +0x538
github.com/mxschmitt/playwright-go.remapMapToStruct(0x134de80, 0xc0026a78f0, 0x12e8e80, 0xc00045b080)
        C:/Users/sicko/go/pkg/mod/github.com/mxschmitt/playwright-go@v0.1100.0/helpers.go:168 +0x167
github.com/mxschmitt/playwright-go.(*browserContextImpl).Cookies(0xc000268900, 0x0, 0x0, 0x0, 0x8, 0x0, 0x93e869, 0x9, 0x203000b)

**Comment by sicko7947** [comment] 2021-04-23 18:59
Error was occured from helpers.go line 136
![image](https://user-images.githubusercontent.com/19926182/115917441-99225080-a4b9-11eb-994b-2b3ba101e615.png)


I didn't take a close look at the issue and I just added a recover() for a temp fix. Please have a look on this one.

**Comment by mxschmitt** [comment] 2021-05-01 09:56
Do you have a full reproducible for it? That would help me to fix this bug, thanks!
@sicko7947

**Comment by sicko7947** [comment] 2021-05-01 11:29
> Do you have a full reproducible for it? That would help me to fix this bug, thanks!
> @sicko7947

It happens casually, try Cookies() at the same time refresh web pages, or perhaps put them into two simultaneous goroutine.

**Comment by mxschmitt** [comment] 2021-08-04 12:26
Closing since we need a reproducible for it. Also Playwright for Go is not "thread-safe". You need to keep its own instance always in the same Go routine otherwise it can lead to unexpected behaviour.

**Closed by mxschmitt** 2021-08-04 12:26 UTC
Labels: needs-verification, p2-bug

**Comment by wujinzhao** [comment] 2023-04-26 02:39
> Closing since we need a reproducible for it. Also Playwright for Go is not "thread-safe". You need to keep its own instance always in the same Go routine otherwise it can lead to unexpected behaviour.

@mxschmitt this cookies
passport_csrf_token=d6e8ccb02b98af2b4c6048fc3f15848e; passport_csrf_token_default=d6e8ccb02b98af2b4c6048fc3f15848e; my_rd=1; csrf_session_id=bf28ee81ea28b6598cc4b98c8ce54e8e; s_v_web_id=lf8046xe_K9Nvv4yq_QGMT_4Ssj_B7rx_AgiczhdlIXtu; LOGIN_STATUS=1; xgplayer_device_id=41584380763; xgplayer_user_id=684581135720; _tea_utm_cache_7497=undefined; strategyABtestKey=%221681971121.948%22; VIDEO_FILTER_MEMO_SELECT=%7B%22expireTime%22%3A1682575921969%2C%22type%22%3A1%7D; home_can_add_dy_2_desktop=%221%22; publish_badge_show_info=%221%2C0%2C0%2C1681971123348%22; download_guide=%221%2F20230420%22; pwa2=%221%7C0%22; passport_assist_user=CkDdOmxuBYFOZGMdL7Pg0TIrBFCjPIx2gUom1vhQcGJCnmS9yzUDL5TAvfzb4c-3jTQKbvVHTF1YH2g69tFK1EUNGkgKPP1v1TKE1WnxGRjVY8O-wXBgXXLt-C7OLY6lC16Q1OL3urUFMiMDsVjK_u-FZ4U-VJDSnz8hsWDsBVk3IhCnnq8NGImv1lQiAQMSPx_M; _tea_utm_cache_2906=undefined; _tea_utm_cache_2562=undefined; tt_scid=oVvPZRimgJntEE-wpD.ZnekhpvSGvYpGBtivPxIXLgQUJdXjdjF80T58hkh1L4ku5b42; msToken=l7st-ezzDPrccB3WTrssUYZTLRheyD6wyIJPfHO2rJT_AKQORefMlUdNal3f8wGBFF388Fo87GNUQiPDgFIY6idUifuiajUr9rCQYY5qBuxKiS5B5ddi_Pgl9A==
